spring.application.name=foundry-api

# For initial local startup only
spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,org.springframework.boot.liquibase.autoconfigure.LiquibaseAutoConfiguration

management.endpoints.web.exposure.include=health,info
